default: &default
  adapter: postgresql
  encoding: unicode
  host: db            # <--- Name of the PostgreSQL container
  username: postgres  # or whatever user you set
  password: password  # match this with docker-compose.yml
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budgy_development

test:
  <<: *default
  database: Budgy_test

production:
  <<: *default
  database: Budgy_production
  username: Budgy
  password: <%= ENV["Budgy_DATABASE_PASSWORD"] %>

