apiVersion: v1
kind: Secret
metadata:
  name: repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/<your-username>/<private-repo>
  username: <your-github-username>
  password: <your-github-token>

